title: La Caosteca - Javi Cepa
description: Creador de muchas cosas y algunas personas.

permalink: ':title/'
# baseurl: "" # the subpath of your site, e.g. /blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://javicepa.com" # the base hostname/protocol, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here


# Author Settings
author: La Caosteca # add your name
author-img: javicepa.png # add your photo
about-author: de Javi Cepa
email: info@pixelatto.com # add your Email address

# Disqus
discus-identifier: javicepa # add your discus identifier

# Tracker
analytics: UA-111462363-1 # Google Analytics

# Build Settings
markdown: kramdown

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
